### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by psychobolt** [rharkor/caching-for-turbo#30]
For Windows, the log file is not created. 

```
Error: ENOENT: no such file or directory, open 'D:\tmp\turbogha.log'
    at openSync (node:fs:573:18)
    at launchServer (D:\a\_actions\rharkor\caching-for-turbo\d030e8813d3de6746943c17def1f5643b1dd1e94\src\lib\server\utils.ts:28:1)
    at run (D:\a\_actions\rharkor\caching-for-turbo\d030e8813d3de6746943c17def1f5643b1dd1e94\src\main.ts:16:1)
    at D:\a\_actions\rharkor\caching-for-turbo\d030e8813d3de6746943c17def1f5643b1dd1e94\src\index.ts:7:1
    at D:\a\_actions\rharkor\caching-for-turbo\d030e8813d3de6746943c17def1f5643b1dd1e94\dist\index.js:1585[12](https://github.com/psychobolt/vite-storybook-boilerplate/actions/runs/9617119273/job/26528200184?pr=920#step:5:13):3
    at Object.<anonymous> (D:\a\_actions\rharkor\caching-for-turbo\d030e88[13](https://github.com/psychobolt/vite-storybook-boilerplate/actions/runs/9617119273/job/26528200184?pr=920#step:5:14)d3de6746943c17def1f5643b1dd1e94\dist\index.js:158515:12)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:[14](https://github.com/psychobolt/vite-storybook-boilerplate/actions/runs/9617119273/job/26528200184?pr=920#step:5:15)16:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
```

Which I also found another bug,
```
Post job cleanup.
D:\a\_actions\rharkor\caching-for-turbo\d030e8813d3de6746943c17def1f5643b1dd1e94\post.js:[2](https://github.com/psychobolt/vite-storybook-boilerplate/actions/runs/9617119273/job/26528200184?pr=920#step:10:2)2
    if (error instanceof Error) core.setFailed(error.message)
                                ^

ReferenceError: core is not defined
    at run (D:\a\_actions\rharkor\caching-for-turbo\d0[3](https://github.com/psychobolt/vite-storybook-boilerplate/actions/runs/9617119273/job/26528200184?pr=920#step:10:3)0e8813d3de6746943c17def1f5643b1dd1e94\post.js:22:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:9[5](https://github.com/psychobolt/vite-storybook-boilerplate/actions/runs/9617119273/job/26528200184?pr=920#step:10:5):5)

Node.js v20.13.1
```

Seeing [here](https://github.com/rharkor/caching-for-turbo/blob/d030e8813d3de6746943c17def1f5643b1dd1e94/post.js#L1) `import * as core from '@actions/core';` is not declared. 

Also would it be ideal for log folder be same as  `runner.temp`? [Reference](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context)

As a workaround for anyone running into the same issue for Windows, you may add this step:
```yml
- name: Create Turbo Cache Server Log
  if: matrix.os == 'windows-latest'
  run: mkdir D:/tmp && touch D:/tmp/turbogha.log || exit 0
  shell: bash
```

**Comment by rharkor** [comment]
Hy @psychobolt , first of all thank you so much for your feedback your issue was really well written !

I fixed my code to use the runner.temp folder as you suggested :wink:

You can take a look at the latest version (v1.2)

Have a good day
